version: '3.8'

services:
  serving:
    build:
      context: .
      dockerfile: Dockerfile.serving
    ports:
      - "5000:5000"
    networks:
      - app-network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    networks:
      - app-network
    depends_on:
      - serving

networks:
  app-network:
    driver: bridge
